jobs:

# Replace params / app_name with your heroku app name
- name: ci
  plan:
  - aggregate:
    - get: heroku-pipeline-app
    - get: heroku-pipeline-infra
      trigger: true
  - task: sync_heroku
    file: heroku-example/concourse/heroku_sync.yml
    input_mapping: {source: heroku-pipeline-app}
    params:
      app_name: sebusk-pipeline
      heroku_email: ((heroku_email))
      heroku_api_token: ((heroku_api_key))

resources:

# Replace with your own repository
- name: heroku-pipeline-app
  type: git
  source:
      uri: https://github.com/SebuskDev/PGR301-heroku-pipeline-app
      branch: master
      private_key: ((deploy_key_app))

# Replace with your own repository
- name: heroku-pipeline-infra
  type: git
  source:
      uri: https://github.com/SebuskDev/PGR301-heroku-pipeline-infra
      branch: master
      private_key: ((deploy_key_infra))
